app:
  jwt:
    secret: "BO3;Y++Qh]ja.x_P`hAvA|)RGct'N?Y.'xy=-,_O.kqhyh>KHl.c#pzZNa'rztZ"
    expiration-minutes: 60

spring:
  application:
    name: your_car_your_way

  datasource:
    url: jdbc:postgresql://localhost:5432/ycyw   # si l'app tourne en local
    username: ycyw_user
    password: ycyw_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
